---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: konflux-e2e-runner
spec:
  description: |
    This task runs E2E tests for the Konflux project using specified parameters
    such as the Git repository URL, revision, and OpenShift login command. It sets up the environment,
    clones the repository, and executes the E2E tests, storing the artifacts in an OCI container registry
    using ORAS.
  params:
    - name: ocp-login-command
      type: string
      description: "Command to log in to the OpenShift cluster."
    - name: test-name
      type: string
      description: "The name of the test being executed."
    - name: git-repo
      type: string
      default: "e2e-tests"
      description: "The name of the Git repository containing the E2E tests."
    - name: git-url
      type: string
      default: "https://github.com/konflux-ci/e2e-tests.git"
      description: "The URL of the Git repository containing the E2E tests."
    - name: git-revision
      type: string
      default: "main"
      description: "The revision (branch or tag) of the Git repository to checkout."
    - name: oras-container
      type: string
      description: "The URI of the OCI container registry to store test artifacts."
      default: "quay.io/org/rhtap-e2e-artifacts"
    - name: job-spec
      type: string
      description: "The job specification containing details of the test execution."
    - name: container-image
      type: string
      description: "Contain the container name from Konflux Snapshot."
      default: "quay.io/redhat-user-workloads/konflux-qe-team-tenant/konflux-e2e/konflux-e2e-tests:latest"
    - name: component-image
      type: string
      description: 'Container image built from any konflux git repo.'
      default: "none"
    - name: ginkgo-procs
      description: "Number of processes to run in parallel in ginkgo"
      default: 20
    - name: sealights-bsid
      description: ""
      default: ""
  volumes:
    - name: konflux-secret-volume
      secret:
        secretName: konflux-e2e-secrets
    - name: konflux-test-infra-volume
      secret:
        secretName: konflux-test-infra
  steps:
    - name: e2e-test
      computeResources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2"
          memory: "6Gi"
      image: $(params.container-image)
      volumeMounts:
        - name: konflux-secret-volume
          mountPath: /usr/local/konflux-ci-secrets
        - name:  konflux-test-infra-volume
          mountPath: /usr/local/konflux-test-infra
      workingDir: /workspace/e2e-tests
      env:
        - name: JOB_NAME
          value: $(params.test-name)
        - name: GIT_REPO
          value: $(params.git-repo)
        - name: GIT_URL
          value: $(params.git-url)
        - name: GIT_REVISION
          value: $(params.git-revision)
        - name: KONFLUX_CI
          value: "true"
        - name: JOB_SPEC
          value: $(params.job-spec)
        - name: COMPONENT_IMAGE
          value: $(params.component-image)
        - name: GINKGO_PROCS
          value: $(params.ginkgo-procs)
        - name: ORAS_CONTAINER
          value: $(params.oras-container)
        - name: ARTIFACT_DIR
          value: /workspace/artifact-dir
        - name: BUILD_SESSION_ID
          value: $(params.sealights-bsid)
      onError: continue
      script: |
        #!/bin/bash

        echo "Running from flavius fork with BSID = $BUILD_SESSION_ID"

        post_actions() {
            local exit_code=$?

            exit "$exit_code"
        }

        trap post_actions EXIT

        log() {
            echo -e "[$(date +'%Y-%m-%d %H:%M:%S')] [$1] $2"
        }
        export -f log

        # Log into OpenShift cluster (the connection is sometimes flaky - give it more time)
        timeout --foreground "10m" bash -c "
        until $(params.ocp-login-command)
        do
            echo \"Waiting for 'oc login' command to succeed... Trying again in 10 seconds\"
            sleep 10
        done
        "

        export GITHUB_TOKEN

        PREVIOUS_RATE_REMAINING=0

        IFS=',' read -r -a GITHUB_ACCOUNTS_ARRAY <<< "$(cat /usr/local/konflux-ci-secrets/github_accounts)"
        for account in "${GITHUB_ACCOUNTS_ARRAY[@]}"; do
            IFS=':' read -r -a GITHUB_USERNAME_ARRAY <<< "$account"

            GH_RATE_REMAINING=$(curl -s \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${GITHUB_USERNAME_ARRAY[1]}" \
                https://api.github.com/rate_limit | jq ".rate.remaining")

            log "INFO" "user: ${GITHUB_USERNAME_ARRAY[0]} with rate limit remaining $GH_RATE_REMAINING"
            if [[ "$GH_RATE_REMAINING" -ge "$PREVIOUS_RATE_REMAINING" ]]; then
                GITHUB_USER="${GITHUB_USERNAME_ARRAY[0]}"
                GITHUB_TOKEN="${GITHUB_USERNAME_ARRAY[1]}"
            fi
            PREVIOUS_RATE_REMAINING="$GH_RATE_REMAINING"
        done

        log "INFO" "running tests with github user: ${GITHUB_USER}"

        # Prepare git, pair branch if necessary, Install Konflux and run e2e tests
        cd "$(mktemp -d)"

        git config --global user.name "redhat-appstudio-qe-bot"
        git config --global user.email redhat-appstudio-qe-bot@redhat.com

        mkdir -p "${HOME}/creds"
        git_creds_path="${HOME}/creds/file"
        git config --global credential.helper "store --file $git_creds_path"
        echo "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com" > "$git_creds_path"


        git clone -b intg_sl "https://github.com/flacatus/e2e-tests.git" .
        /bin/bash -c "integration-tests/scripts/konflux-e2e-runner.sh" || true

        export DOMAIN="redhat.sealights.co"
        export SEALIGHTS_AGENT_TOKEN="${SEALIGHTS_AGENT_TOKEN:-""}"
        export BUILD_SESSION_ID="${BUILD_SESSION_ID:-""}"

        # Create a Sealights test session
        echo "INFO: Creating Sealights test session..."
        TEST_SESSION_ID=$(curl -X POST "https://$DOMAIN/sl-api/v1/test-sessions" \
          -H "Authorization: Bearer $SEALIGHTS_AGENT_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{"labId":"","testStage":"integration-service-e2e","bsid":"'${BUILD_SESSION_ID}'","sessionTimeout":10000}' | jq -r '.data.testSessionId')

        if [ -n "$TEST_SESSION_ID" ]; then
          echo "Test session ID: $TEST_SESSION_ID"
          export TEST_SESSION_ID
        else
          echo "Failed to retrieve test session ID"
          exit 1
        fi

        # Fetch excluded tests
        RESPONSE=$(curl -X GET "https://$DOMAIN/sl-api/v2/test-sessions/$TEST_SESSION_ID/exclude-tests" \
          -H "Authorization: Bearer $SEALIGHTS_AGENT_TOKEN" \
          -H "Content-Type: application/json")

        echo "$RESPONSE" | jq .

        # Extract excluded tests
        mapfile -t EXCLUDED_TESTS < <(echo "$RESPONSE" | jq -r '.data.excludedTests[].testName')

        # Process test report
        PROCESSED_JSON=$(
          cat "$ARTIFACT_DIR"/e2e-report.json | jq -c '.[] | .SpecReports[]' | while IFS= read -r line; do
            name=$(echo "$line" | jq -r '.LeafNodeText')
            start_raw=$(echo "$line" | jq -r '.StartTime')
            end_raw=$(echo "$line" | jq -r '.EndTime')
            status=$(echo "$line" | jq -r '.State')

            # Process start time with `date`
            start=$(date --date="$start_raw" +%s%3N)

            # Check if end_raw is empty or equals "0001-01-01T00:00:00Z", and use the current time
            if [ -z "$end_raw" ] || [ "$end_raw" == "0001-01-01T00:00:00Z" ]; then
              end=$(date +%s%3N)
            else
              end=$(date --date="$end_raw" +%s%3N)
            fi

            if [ "$status" == "passed" ] || [ "$status" == "failed" ]; then
              echo "{\"name\": \"$name\", \"start\": $start, \"end\": $end, \"status\": \"$status\"}"
            fi
          done | jq -s '.'
        )

        echo "$PROCESSED_JSON" | jq .

        # Send test results to Sealights
        curl -X POST "https://$DOMAIN/sl-api/v2/test-sessions/$TEST_SESSION_ID" \
          -H "Authorization: Bearer $SEALIGHTS_AGENT_TOKEN" \
          -H "Content-Type: application/json" \
          -d "${PROCESSED_JSON}"

        # Delete the test session
        curl -X DELETE "https://$DOMAIN/sl-api/v1/test-sessions/$TEST_SESSION_ID" \
          -H "Authorization: Bearer $SEALIGHTS_AGENT_TOKEN" \
          -H "Content-Type: application/json"

        echo "INFO: Script completed successfully."

    - name: secure-push-oci
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/secure-push-oci/0.1/secure-push-oci.yaml
      params:
        - name: workdir-path
          value: /workspace/artifact-dir
        - name: oci-ref
          value: $(params.oras-container)
        - name: credentials-volume-name
          value: konflux-test-infra-volume
    - name: fail-if-any-step-failed
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/fail-if-any-step-failed/0.1/fail-if-any-step-failed.yaml
